/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAddRouteImport } from './routes/_app/add'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppLoansRouteImport } from './routes/_app/loans'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppWishlistRouteImport } from './routes/_app/wishlist'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AppBooksIndexRouteImport } from './routes/_app/books.index'
import { Route as AppBooksBookIdRouteImport } from './routes/_app/books.$bookId'
import { Route as AppBooksNewRouteImport } from './routes/_app/books.new'
import { Route as AppInviteTokenRouteImport } from './routes/_app/invite.$token'
import { Route as AppLibrariesIndexRouteImport } from './routes/_app/libraries.index'
import { Route as AppSeriesIndexRouteImport } from './routes/_app/series.index'
import { Route as AppSeriesSeriesIdRouteImport } from './routes/_app/series.$seriesId'
import { Route as AppShelvesShelfIdRouteImport } from './routes/_app/shelves.$shelfId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiCoversBookIdRouteImport } from './routes/api/covers.$bookId'
import { Route as AppBooksBookIdEditRouteImport } from './routes/_app/books_.$bookId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdRoute = AppBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksNewRoute = AppBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppLibrariesIndexRoute = AppLibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesSeriesIdRoute = AppSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => AppRoute,
} as any)
const AppShelvesShelfIdRoute = AppShelvesShelfIdRouteImport.update({
  id: '/shelves/$shelfId',
  path: '/shelves/$shelfId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversBookIdRoute = ApiCoversBookIdRouteImport.update({
  id: '/api/covers/$bookId',
  path: '/api/covers/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksBookIdEditRoute = AppBooksBookIdEditRouteImport.update({
  id: '/books_/$bookId/edit',
  path: '/books/$bookId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add': typeof AppAddRoute
  '/friends': typeof AppFriendsRoute
  '/loans': typeof AppLoansRoute
  '/requests': typeof AppRequestsRoute
  '/wishlist': typeof AppWishlistRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/books/': typeof AppBooksIndexRoute
  '/libraries/': typeof AppLibrariesIndexRoute
  '/series/': typeof AppSeriesIndexRoute
  '/books/$bookId/edit': typeof AppBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add': typeof AppAddRoute
  '/friends': typeof AppFriendsRoute
  '/loans': typeof AppLoansRoute
  '/requests': typeof AppRequestsRoute
  '/wishlist': typeof AppWishlistRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/books': typeof AppBooksIndexRoute
  '/libraries': typeof AppLibrariesIndexRoute
  '/series': typeof AppSeriesIndexRoute
  '/books/$bookId/edit': typeof AppBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/add': typeof AppAddRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/wishlist': typeof AppWishlistRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/_app/books/$bookId': typeof AppBooksBookIdRoute
  '/_app/books/new': typeof AppBooksNewRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/_app/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/_app/books/': typeof AppBooksIndexRoute
  '/_app/libraries/': typeof AppLibrariesIndexRoute
  '/_app/series/': typeof AppSeriesIndexRoute
  '/_app/books_/$bookId/edit': typeof AppBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add'
    | '/friends'
    | '/loans'
    | '/requests'
    | '/wishlist'
    | '/join/$token'
    | '/s/$token'
    | '/books/$bookId'
    | '/books/new'
    | '/invite/$token'
    | '/series/$seriesId'
    | '/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/books/'
    | '/libraries/'
    | '/series/'
    | '/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/add'
    | '/friends'
    | '/loans'
    | '/requests'
    | '/wishlist'
    | '/join/$token'
    | '/s/$token'
    | '/books/$bookId'
    | '/books/new'
    | '/invite/$token'
    | '/series/$seriesId'
    | '/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/books'
    | '/libraries'
    | '/series'
    | '/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/add'
    | '/_app/friends'
    | '/_app/loans'
    | '/_app/requests'
    | '/_app/wishlist'
    | '/join/$token'
    | '/s/$token'
    | '/_app/books/$bookId'
    | '/_app/books/new'
    | '/_app/invite/$token'
    | '/_app/series/$seriesId'
    | '/_app/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/_app/books/'
    | '/_app/libraries/'
    | '/_app/series/'
    | '/_app/books_/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinTokenRoute: typeof JoinTokenRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversBookIdRoute: typeof ApiCoversBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishlist': {
      id: '/_app/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId': {
      id: '/_app/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppBooksBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/new': {
      id: '/_app/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AppBooksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libraries/': {
      id: '/_app/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AppLibrariesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/': {
      id: '/_app/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/$seriesId': {
      id: '/_app/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AppSeriesSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shelves/$shelfId': {
      id: '/_app/shelves/$shelfId'
      path: '/shelves/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof AppShelvesShelfIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$bookId': {
      id: '/api/covers/$bookId'
      path: '/api/covers/$bookId'
      fullPath: '/api/covers/$bookId'
      preLoaderRoute: typeof ApiCoversBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/books_/$bookId/edit': {
      id: '/_app/books_/$bookId/edit'
      path: '/books/$bookId/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof AppBooksBookIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppBooksBookIdRoute: typeof AppBooksBookIdRoute
  AppBooksNewRoute: typeof AppBooksNewRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppSeriesSeriesIdRoute: typeof AppSeriesSeriesIdRoute
  AppShelvesShelfIdRoute: typeof AppShelvesShelfIdRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppLibrariesIndexRoute: typeof AppLibrariesIndexRoute
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
  AppBooksBookIdEditRoute: typeof AppBooksBookIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppLoansRoute: AppLoansRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppBooksBookIdRoute: AppBooksBookIdRoute,
  AppBooksNewRoute: AppBooksNewRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppSeriesSeriesIdRoute: AppSeriesSeriesIdRoute,
  AppShelvesShelfIdRoute: AppShelvesShelfIdRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppLibrariesIndexRoute: AppLibrariesIndexRoute,
  AppSeriesIndexRoute: AppSeriesIndexRoute,
  AppBooksBookIdEditRoute: AppBooksBookIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinTokenRoute: JoinTokenRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversBookIdRoute: ApiCoversBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
