/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as AppAddRouteImport } from './routes/_app/add'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppLoansRouteImport } from './routes/_app/loans'
import { Route as AppReadingRouteImport } from './routes/_app/reading'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppServiceRouteImport } from './routes/_app/service'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUnrecognizedRouteImport } from './routes/_app/unrecognized'
import { Route as AppUnsortedRouteImport } from './routes/_app/unsorted'
import { Route as AppWishlistRouteImport } from './routes/_app/wishlist'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AppAuthorsAuthorIdRouteImport } from './routes/_app/authors.$authorId'
import { Route as AppBooksIndexRouteImport } from './routes/_app/books.index'
import { Route as AppBooksBookIdRouteImport } from './routes/_app/books.$bookId'
import { Route as AppBooksNewRouteImport } from './routes/_app/books.new'
import { Route as AppEditionsRefBookIdRouteImport } from './routes/_app/editions.$refBookId'
import { Route as AppInviteTokenRouteImport } from './routes/_app/invite.$token'
import { Route as AppLibrariesIndexRouteImport } from './routes/_app/libraries.index'
import { Route as AppListsListIdRouteImport } from './routes/_app/lists.$listId'
import { Route as AppSeriesIndexRouteImport } from './routes/_app/series.index'
import { Route as AppSeriesSeriesIdRouteImport } from './routes/_app/series.$seriesId'
import { Route as AppServiceAiRouteImport } from './routes/_app/service_.ai'
import { Route as AppServiceLogRouteImport } from './routes/_app/service_.log'
import { Route as AppServiceMailRouteImport } from './routes/_app/service_.mail'
import { Route as AppServiceQueueRouteImport } from './routes/_app/service_.queue'
import { Route as AppServiceSourcesRouteImport } from './routes/_app/service_.sources'
import { Route as AppServiceUsersRouteImport } from './routes/_app/service_.users'
import { Route as AppShelvesShelfIdRouteImport } from './routes/_app/shelves.$shelfId'
import { Route as AppWorksWorkIdRouteImport } from './routes/_app/works.$workId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiCoversBookIdRouteImport } from './routes/api/covers.$bookId'
import { Route as ApiRefCoversRefBookIdRouteImport } from './routes/api/ref-covers.$refBookId'
import { Route as AppBooksBookIdEditRouteImport } from './routes/_app/books_.$bookId.edit'
import { Route as AppListsListIdEditRouteImport } from './routes/_app/lists_.$listId.edit'
import { Route as ApiAuthorsAuthorIdPhotoRouteImport } from './routes/api/authors.$authorId.photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingRoute = AppReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUnrecognizedRoute = AppUnrecognizedRouteImport.update({
  id: '/unrecognized',
  path: '/unrecognized',
  getParentRoute: () => AppRoute,
} as any)
const AppUnsortedRoute = AppUnsortedRouteImport.update({
  id: '/unsorted',
  path: '/unsorted',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthorsAuthorIdRoute = AppAuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdRoute = AppBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksNewRoute = AppBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEditionsRefBookIdRoute = AppEditionsRefBookIdRouteImport.update({
  id: '/editions/$refBookId',
  path: '/editions/$refBookId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppLibrariesIndexRoute = AppLibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => AppRoute,
} as any)
const AppListsListIdRoute = AppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesSeriesIdRoute = AppSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceAiRoute = AppServiceAiRouteImport.update({
  id: '/service_/ai',
  path: '/service/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceLogRoute = AppServiceLogRouteImport.update({
  id: '/service_/log',
  path: '/service/log',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceMailRoute = AppServiceMailRouteImport.update({
  id: '/service_/mail',
  path: '/service/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceQueueRoute = AppServiceQueueRouteImport.update({
  id: '/service_/queue',
  path: '/service/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceSourcesRoute = AppServiceSourcesRouteImport.update({
  id: '/service_/sources',
  path: '/service/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceUsersRoute = AppServiceUsersRouteImport.update({
  id: '/service_/users',
  path: '/service/users',
  getParentRoute: () => AppRoute,
} as any)
const AppShelvesShelfIdRoute = AppShelvesShelfIdRouteImport.update({
  id: '/shelves/$shelfId',
  path: '/shelves/$shelfId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorksWorkIdRoute = AppWorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversBookIdRoute = ApiCoversBookIdRouteImport.update({
  id: '/api/covers/$bookId',
  path: '/api/covers/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefCoversRefBookIdRoute = ApiRefCoversRefBookIdRouteImport.update({
  id: '/api/ref-covers/$refBookId',
  path: '/api/ref-covers/$refBookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksBookIdEditRoute = AppBooksBookIdEditRouteImport.update({
  id: '/books_/$bookId/edit',
  path: '/books/$bookId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppListsListIdEditRoute = AppListsListIdEditRouteImport.update({
  id: '/lists_/$listId/edit',
  path: '/lists/$listId/edit',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthorsAuthorIdPhotoRoute = ApiAuthorsAuthorIdPhotoRouteImport.update({
  id: '/api/authors/$authorId/photo',
  path: '/api/authors/$authorId/photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/add': typeof AppAddRoute
  '/friends': typeof AppFriendsRoute
  '/loans': typeof AppLoansRoute
  '/reading': typeof AppReadingRoute
  '/requests': typeof AppRequestsRoute
  '/service': typeof AppServiceRoute
  '/settings': typeof AppSettingsRoute
  '/unrecognized': typeof AppUnrecognizedRoute
  '/unsorted': typeof AppUnsortedRoute
  '/wishlist': typeof AppWishlistRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/authors/$authorId': typeof AppAuthorsAuthorIdRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/editions/$refBookId': typeof AppEditionsRefBookIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/service/ai': typeof AppServiceAiRoute
  '/service/log': typeof AppServiceLogRoute
  '/service/mail': typeof AppServiceMailRoute
  '/service/queue': typeof AppServiceQueueRoute
  '/service/sources': typeof AppServiceSourcesRoute
  '/service/users': typeof AppServiceUsersRoute
  '/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/works/$workId': typeof AppWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/ref-covers/$refBookId': typeof ApiRefCoversRefBookIdRoute
  '/books/': typeof AppBooksIndexRoute
  '/libraries/': typeof AppLibrariesIndexRoute
  '/series/': typeof AppSeriesIndexRoute
  '/books/$bookId/edit': typeof AppBooksBookIdEditRoute
  '/lists/$listId/edit': typeof AppListsListIdEditRoute
  '/api/authors/$authorId/photo': typeof ApiAuthorsAuthorIdPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/add': typeof AppAddRoute
  '/friends': typeof AppFriendsRoute
  '/loans': typeof AppLoansRoute
  '/reading': typeof AppReadingRoute
  '/requests': typeof AppRequestsRoute
  '/service': typeof AppServiceRoute
  '/settings': typeof AppSettingsRoute
  '/unrecognized': typeof AppUnrecognizedRoute
  '/unsorted': typeof AppUnsortedRoute
  '/wishlist': typeof AppWishlistRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/authors/$authorId': typeof AppAuthorsAuthorIdRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/editions/$refBookId': typeof AppEditionsRefBookIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/service/ai': typeof AppServiceAiRoute
  '/service/log': typeof AppServiceLogRoute
  '/service/mail': typeof AppServiceMailRoute
  '/service/queue': typeof AppServiceQueueRoute
  '/service/sources': typeof AppServiceSourcesRoute
  '/service/users': typeof AppServiceUsersRoute
  '/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/works/$workId': typeof AppWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/ref-covers/$refBookId': typeof ApiRefCoversRefBookIdRoute
  '/books': typeof AppBooksIndexRoute
  '/libraries': typeof AppLibrariesIndexRoute
  '/series': typeof AppSeriesIndexRoute
  '/books/$bookId/edit': typeof AppBooksBookIdEditRoute
  '/lists/$listId/edit': typeof AppListsListIdEditRoute
  '/api/authors/$authorId/photo': typeof ApiAuthorsAuthorIdPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/rules': typeof RulesRoute
  '/_app/add': typeof AppAddRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/reading': typeof AppReadingRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/service': typeof AppServiceRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/unrecognized': typeof AppUnrecognizedRoute
  '/_app/unsorted': typeof AppUnsortedRoute
  '/_app/wishlist': typeof AppWishlistRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$token': typeof JoinTokenRoute
  '/s/$token': typeof STokenRoute
  '/_app/authors/$authorId': typeof AppAuthorsAuthorIdRoute
  '/_app/books/$bookId': typeof AppBooksBookIdRoute
  '/_app/books/new': typeof AppBooksNewRoute
  '/_app/editions/$refBookId': typeof AppEditionsRefBookIdRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/lists/$listId': typeof AppListsListIdRoute
  '/_app/series/$seriesId': typeof AppSeriesSeriesIdRoute
  '/_app/service_/ai': typeof AppServiceAiRoute
  '/_app/service_/log': typeof AppServiceLogRoute
  '/_app/service_/mail': typeof AppServiceMailRoute
  '/_app/service_/queue': typeof AppServiceQueueRoute
  '/_app/service_/sources': typeof AppServiceSourcesRoute
  '/_app/service_/users': typeof AppServiceUsersRoute
  '/_app/shelves/$shelfId': typeof AppShelvesShelfIdRoute
  '/_app/works/$workId': typeof AppWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/ref-covers/$refBookId': typeof ApiRefCoversRefBookIdRoute
  '/_app/books/': typeof AppBooksIndexRoute
  '/_app/libraries/': typeof AppLibrariesIndexRoute
  '/_app/series/': typeof AppSeriesIndexRoute
  '/_app/books_/$bookId/edit': typeof AppBooksBookIdEditRoute
  '/_app/lists_/$listId/edit': typeof AppListsListIdEditRoute
  '/api/authors/$authorId/photo': typeof ApiAuthorsAuthorIdPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/reset'
    | '/rules'
    | '/add'
    | '/friends'
    | '/loans'
    | '/reading'
    | '/requests'
    | '/service'
    | '/settings'
    | '/unrecognized'
    | '/unsorted'
    | '/wishlist'
    | '/api/health'
    | '/join/$token'
    | '/s/$token'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/books/new'
    | '/editions/$refBookId'
    | '/invite/$token'
    | '/lists/$listId'
    | '/series/$seriesId'
    | '/service/ai'
    | '/service/log'
    | '/service/mail'
    | '/service/queue'
    | '/service/sources'
    | '/service/users'
    | '/shelves/$shelfId'
    | '/works/$workId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/api/ref-covers/$refBookId'
    | '/books/'
    | '/libraries/'
    | '/series/'
    | '/books/$bookId/edit'
    | '/lists/$listId/edit'
    | '/api/authors/$authorId/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/reset'
    | '/rules'
    | '/add'
    | '/friends'
    | '/loans'
    | '/reading'
    | '/requests'
    | '/service'
    | '/settings'
    | '/unrecognized'
    | '/unsorted'
    | '/wishlist'
    | '/api/health'
    | '/join/$token'
    | '/s/$token'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/books/new'
    | '/editions/$refBookId'
    | '/invite/$token'
    | '/lists/$listId'
    | '/series/$seriesId'
    | '/service/ai'
    | '/service/log'
    | '/service/mail'
    | '/service/queue'
    | '/service/sources'
    | '/service/users'
    | '/shelves/$shelfId'
    | '/works/$workId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/api/ref-covers/$refBookId'
    | '/books'
    | '/libraries'
    | '/series'
    | '/books/$bookId/edit'
    | '/lists/$listId/edit'
    | '/api/authors/$authorId/photo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot'
    | '/login'
    | '/reset'
    | '/rules'
    | '/_app/add'
    | '/_app/friends'
    | '/_app/loans'
    | '/_app/reading'
    | '/_app/requests'
    | '/_app/service'
    | '/_app/settings'
    | '/_app/unrecognized'
    | '/_app/unsorted'
    | '/_app/wishlist'
    | '/api/health'
    | '/join/$token'
    | '/s/$token'
    | '/_app/authors/$authorId'
    | '/_app/books/$bookId'
    | '/_app/books/new'
    | '/_app/editions/$refBookId'
    | '/_app/invite/$token'
    | '/_app/lists/$listId'
    | '/_app/series/$seriesId'
    | '/_app/service_/ai'
    | '/_app/service_/log'
    | '/_app/service_/mail'
    | '/_app/service_/queue'
    | '/_app/service_/sources'
    | '/_app/service_/users'
    | '/_app/shelves/$shelfId'
    | '/_app/works/$workId'
    | '/api/auth/$'
    | '/api/covers/$bookId'
    | '/api/ref-covers/$refBookId'
    | '/_app/books/'
    | '/_app/libraries/'
    | '/_app/series/'
    | '/_app/books_/$bookId/edit'
    | '/_app/lists_/$listId/edit'
    | '/api/authors/$authorId/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  RulesRoute: typeof RulesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  JoinTokenRoute: typeof JoinTokenRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoversBookIdRoute: typeof ApiCoversBookIdRoute
  ApiRefCoversRefBookIdRoute: typeof ApiRefCoversRefBookIdRoute
  ApiAuthorsAuthorIdPhotoRoute: typeof ApiAuthorsAuthorIdPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading': {
      id: '/_app/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AppReadingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service': {
      id: '/_app/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unrecognized': {
      id: '/_app/unrecognized'
      path: '/unrecognized'
      fullPath: '/unrecognized'
      preLoaderRoute: typeof AppUnrecognizedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unsorted': {
      id: '/_app/unsorted'
      path: '/unsorted'
      fullPath: '/unsorted'
      preLoaderRoute: typeof AppUnsortedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishlist': {
      id: '/_app/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/authors/$authorId': {
      id: '/_app/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AppAuthorsAuthorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId': {
      id: '/_app/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppBooksBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/new': {
      id: '/_app/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AppBooksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editions/$refBookId': {
      id: '/_app/editions/$refBookId'
      path: '/editions/$refBookId'
      fullPath: '/editions/$refBookId'
      preLoaderRoute: typeof AppEditionsRefBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/libraries/': {
      id: '/_app/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AppLibrariesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/$listId': {
      id: '/_app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AppListsListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/': {
      id: '/_app/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/$seriesId': {
      id: '/_app/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AppSeriesSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/ai': {
      id: '/_app/service_/ai'
      path: '/service/ai'
      fullPath: '/service/ai'
      preLoaderRoute: typeof AppServiceAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/log': {
      id: '/_app/service_/log'
      path: '/service/log'
      fullPath: '/service/log'
      preLoaderRoute: typeof AppServiceLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/mail': {
      id: '/_app/service_/mail'
      path: '/service/mail'
      fullPath: '/service/mail'
      preLoaderRoute: typeof AppServiceMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/queue': {
      id: '/_app/service_/queue'
      path: '/service/queue'
      fullPath: '/service/queue'
      preLoaderRoute: typeof AppServiceQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/sources': {
      id: '/_app/service_/sources'
      path: '/service/sources'
      fullPath: '/service/sources'
      preLoaderRoute: typeof AppServiceSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service_/users': {
      id: '/_app/service_/users'
      path: '/service/users'
      fullPath: '/service/users'
      preLoaderRoute: typeof AppServiceUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shelves/$shelfId': {
      id: '/_app/shelves/$shelfId'
      path: '/shelves/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof AppShelvesShelfIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/works/$workId': {
      id: '/_app/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof AppWorksWorkIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$bookId': {
      id: '/api/covers/$bookId'
      path: '/api/covers/$bookId'
      fullPath: '/api/covers/$bookId'
      preLoaderRoute: typeof ApiCoversBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ref-covers/$refBookId': {
      id: '/api/ref-covers/$refBookId'
      path: '/api/ref-covers/$refBookId'
      fullPath: '/api/ref-covers/$refBookId'
      preLoaderRoute: typeof ApiRefCoversRefBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/books_/$bookId/edit': {
      id: '/_app/books_/$bookId/edit'
      path: '/books/$bookId/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof AppBooksBookIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists_/$listId/edit': {
      id: '/_app/lists_/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof AppListsListIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/authors/$authorId/photo': {
      id: '/api/authors/$authorId/photo'
      path: '/api/authors/$authorId/photo'
      fullPath: '/api/authors/$authorId/photo'
      preLoaderRoute: typeof ApiAuthorsAuthorIdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppReadingRoute: typeof AppReadingRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppServiceRoute: typeof AppServiceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUnrecognizedRoute: typeof AppUnrecognizedRoute
  AppUnsortedRoute: typeof AppUnsortedRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppAuthorsAuthorIdRoute: typeof AppAuthorsAuthorIdRoute
  AppBooksBookIdRoute: typeof AppBooksBookIdRoute
  AppBooksNewRoute: typeof AppBooksNewRoute
  AppEditionsRefBookIdRoute: typeof AppEditionsRefBookIdRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppSeriesSeriesIdRoute: typeof AppSeriesSeriesIdRoute
  AppServiceAiRoute: typeof AppServiceAiRoute
  AppServiceLogRoute: typeof AppServiceLogRoute
  AppServiceMailRoute: typeof AppServiceMailRoute
  AppServiceQueueRoute: typeof AppServiceQueueRoute
  AppServiceSourcesRoute: typeof AppServiceSourcesRoute
  AppServiceUsersRoute: typeof AppServiceUsersRoute
  AppShelvesShelfIdRoute: typeof AppShelvesShelfIdRoute
  AppWorksWorkIdRoute: typeof AppWorksWorkIdRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppLibrariesIndexRoute: typeof AppLibrariesIndexRoute
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
  AppBooksBookIdEditRoute: typeof AppBooksBookIdEditRoute
  AppListsListIdEditRoute: typeof AppListsListIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppLoansRoute: AppLoansRoute,
  AppReadingRoute: AppReadingRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppServiceRoute: AppServiceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUnrecognizedRoute: AppUnrecognizedRoute,
  AppUnsortedRoute: AppUnsortedRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppAuthorsAuthorIdRoute: AppAuthorsAuthorIdRoute,
  AppBooksBookIdRoute: AppBooksBookIdRoute,
  AppBooksNewRoute: AppBooksNewRoute,
  AppEditionsRefBookIdRoute: AppEditionsRefBookIdRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppSeriesSeriesIdRoute: AppSeriesSeriesIdRoute,
  AppServiceAiRoute: AppServiceAiRoute,
  AppServiceLogRoute: AppServiceLogRoute,
  AppServiceMailRoute: AppServiceMailRoute,
  AppServiceQueueRoute: AppServiceQueueRoute,
  AppServiceSourcesRoute: AppServiceSourcesRoute,
  AppServiceUsersRoute: AppServiceUsersRoute,
  AppShelvesShelfIdRoute: AppShelvesShelfIdRoute,
  AppWorksWorkIdRoute: AppWorksWorkIdRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppLibrariesIndexRoute: AppLibrariesIndexRoute,
  AppSeriesIndexRoute: AppSeriesIndexRoute,
  AppBooksBookIdEditRoute: AppBooksBookIdEditRoute,
  AppListsListIdEditRoute: AppListsListIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  RulesRoute: RulesRoute,
  ApiHealthRoute: ApiHealthRoute,
  JoinTokenRoute: JoinTokenRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoversBookIdRoute: ApiCoversBookIdRoute,
  ApiRefCoversRefBookIdRoute: ApiRefCoversRefBookIdRoute,
  ApiAuthorsAuthorIdPhotoRoute: ApiAuthorsAuthorIdPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
